### PR TITLE
Allow for any modern activesupport version

### PR DESCRIPTION
**Pull request by loganmeetsworld**
## What

Allows compatibility with ActiveSupport/Rails versions higher than 4.

### CODE REVIEW

**Comment by loganmeetsworld** [comment]
[Rails 5](https://trello.com/c/aiZ7HguI/1209-rails-5)

**Comment by fredbenenson** [comment]
👍

**Comment by selftext** [comment]
Lol. Hi @fredbenenson!

**Comment by fredbenenson** [comment]
@selftext 👻 📊 ✉️

**Pull request merged**
